/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intellidrive_iscsi_IntellidriveBlockDeviceController */

#ifndef _Included_com_intellidrive_iscsi_IntellidriveBlockDeviceController
#define _Included_com_intellidrive_iscsi_IntellidriveBlockDeviceController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intellidrive_iscsi_IntellidriveBlockDeviceController
 * Method:    getBlockSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_intellidrive_iscsi_IntellidriveBlockDeviceController_getBlockSize
  (JNIEnv *, jobject);

/*
 * Class:     com_intellidrive_iscsi_IntellidriveBlockDeviceController
 * Method:    getDeviceSize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_intellidrive_iscsi_IntellidriveBlockDeviceController_getDeviceSize
  (JNIEnv *, jobject);

/*
 * Class:     com_intellidrive_iscsi_IntellidriveBlockDeviceController
 * Method:    getNumBlocks
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_intellidrive_iscsi_IntellidriveBlockDeviceController_getNumBlocks
  (JNIEnv *, jobject);

/*
 * Class:     com_intellidrive_iscsi_IntellidriveBlockDeviceController
 * Method:    readBlocks
 * Signature: (JI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_intellidrive_iscsi_IntellidriveBlockDeviceController_readBlocks
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_intellidrive_iscsi_IntellidriveBlockDeviceController
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intellidrive_iscsi_IntellidriveBlockDeviceController_shutdown
  (JNIEnv *, jobject);

/*
 * Class:     com_intellidrive_iscsi_IntellidriveBlockDeviceController
 * Method:    startup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intellidrive_iscsi_IntellidriveBlockDeviceController_startup
  (JNIEnv *, jobject);

/*
 * Class:     com_intellidrive_iscsi_IntellidriveBlockDeviceController
 * Method:    writeBlocks
 * Signature: (JI[B)V
 */
JNIEXPORT void JNICALL Java_com_intellidrive_iscsi_IntellidriveBlockDeviceController_writeBlocks
  (JNIEnv *, jobject, jlong, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
